const categories = {
  electronics: [
    "Audio Equipment",
    "Camera and Camera Equipment",
    "Car Electronics and GPS",
    "Computer Accessories",
    "Desktop Computer and Monitors",
    "Laptop and Notebooks",
    "Lighting Equipment",
    "Smartphones and Phone Accessories",
    "Tablets and E-Readers",
    "Storage Devices",
    "Television and Television Services",
    "Video Games and Consoles",
    "Wearable Technology",
    "Watch Accessories",
  ],
  artsAndCraft: [],
  personalCare: [
    "Baby Care Products",
    "Cosmetics",
    "Depilatories",
    "Eye Care and Eye wear",
    "Feminine Hygiene Products",
    "Fragrances",
    "Hair Care Products",
    "Men's Grooming Products",
    "Oral Care Products",
    "Skin Care Products",
    "Soap, Bath and Shower Products",
  ],
  clothing: {
    "Women's Clothing": [
      "Dresses",
      "Blouses & Shirts",
      "Shorts",
      "Jeans",
      "Skirts",
      "Sweaters",
      "Coats & Jackets",
      "Tops & Tees",
      "Pants",
      "Underwear",
      "Swim wears",
      "Women's Sets",
      "Socks",
    ],
    "Men's Clothing": [
      "Top & Tees",
      "Shirts",
      "",
      "Sweaters",
      "Men's Sets",
      "Socks",
      "Jeans",
      "Pants",
      "Underwear",
      "Suits & Blazer",
      "Shorts",
      "Hoodies & Sweatshirts",
    ],
    Culture: ["Muslim Fashion", "Tanzania Clothing", "Africa Clothing"],
    Accessories: [
      "Sunglasses",
      "Hats & Caps",
      "Belts",
      "Gloves and Mittens",
      "Scarves & Wraps",
      "Ties",
      "Other Accessories",
    ],
    Sportswear: ["Jerseys", "Clothing Sets", "Pants", "Other Sportswear"],
    "Jewelery and Watches": [],
  },
  householdAndFurniture: [
    "Furniture",
    "Gardening Supplies and Equipment",
    "Home Security and Safety",
    "Household Cleaners",
    "Office Supplies and Equipment",
    "Pest Control Products",
  ],
  sportsAndEntertainment: [
    "Angling and Hunting Equipment",
    "Mens",
    "Women",
    "Bikes and Cycling Equipment",
    "Golf Equipment",
    "Tennis and Racket Sports Equipment",
    "Video Games and Consoles",
  ],
  shoes: {
    "Women's Shoes": [
      "Sandals & Flip Flops",
      "Nude Shoes",
      "Sneakers",
      "Doug Shoes",
      "Loafers",
      "Canvas Shoes",
      "Boots",
      "Slippers",
      "Other Women's Shoe",
    ],
    "Men's Shoes": [
      "Sneakers",
      "Business Shoes",
      "Doug Shoes",
      "Loafers",
      "Canvas Shoes",
      "Boots",
      " Sandals & Flip Flops",
      "Slippers",
      "Other Men's Shoe",
    ],
    "Shoe Accessories": ["Insoles", "Other Shoe Accessories"],
  },
  babyAndChild: [],
  toys: [],
  retail: [
    "Convenience Stores and Services Stations",
    "Department Stores",
    "Discount Retail",
    "Drugstores and Pharmacies",
    "Duty Free",
    "Electronics Device Retailing",
    "Electronics Retailing, Mail Order and Catalog",
    "Food and Grocery Retailing",
    "Furniture Retailing",
    "Home Centers and Hardware Stores",
    "Supermarkets",
    "Superstores",
  ],
  luggageAndBags: {
    "Women's Bags": [],
    "Men's Bags": [],
    "Other Bags & Accessories": [],
  },
  audioAndVideo: ["Home Audio and Video", "Portable Audio and Video"],
  Services: [
    "Fitness Centers and Health Clubs",
    "Florists",
    "Funeral Services",
    "Hair and Beauty Services",
    "Interior Design and Decorative Arts",
    "Landscaping Services",
    "Laundromats and Dry Cleaners",
    "Pet Care and Services",
    "Photography Services",
  ],
};

module.exports = categories;